spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eastbranchmanagement
    username: eastbranchmanager
    password: triforce
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
    schemas: accounts
security:
  issuer: east bank manager
  lifetime: 15
  secret: bank secret
server:
  port: 7490
