spring:
  #  set connection to database
  datasource:
    url: jdbc:postgresql://localhost:5432/eastbranchmanagement
    username: eastbranchmanager
    password: triforce
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    #    anti-pattern
    open-in-view: false
    #    no automatic actions with schema
    hibernate:
      ddl-auto: none
  #  set state to database through migrations
  flyway:
    locations: classpath:migration
    #    table "user" is reserved for public schema
    schemas: accounts

server:
  port: 7490
